routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Symfony\Component\Routing\Route;
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'function',  'middleware' => 'auth'], function(){
    Route::get('loggedIn', 'FunctionController@loggedIn');
});
Route::group(['prefix' => 'superAdmin',  'middleware' => 'role.superAdmin'], function(){
    Route::resource('dataSekolah', 'AppController\DataSekolahController', [
    ]);
    Route::resource('administratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataPengawas', 'AppController\DataPengawasController', [
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::post('/dataSiswa/store_excel', 'AppController\DataSiswaController@store_excel')->name('siswa_store_excel');
    Route::resource('dataSiswa', 'AppController\DataSiswaController');
    Route::resource('dataJurusan', 'AppController\DataJurusanController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");
=======

    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'guru', 'middleware' => 'role.guru'], function(){
<<<<<<< HEAD
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/dokumen', 'AppController\DataDokumenController@index')->name('dokumenGuruIndex');
    Route::post('/dokumen', 'AppController\DataDokumenController@proses_upload')->name('dokumenGuruPost');
=======


    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/upload', 'AppController\DataDokumenController@upload');
    Route::post('/upload/proses', 'AppController\DataDokumenController@proses_upload');



>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'admin', 'middleware' => 'role.admin'], function(){
<<<<<<< HEAD
    
=======


    Route::resource('dataMapel', 'AppController\DataMapelController');

    Route::resource('tahunAkademik', 'AppController\TahunAkademikController');

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
    Route::resource('AdministratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::resource('dataSiswa', 'AppController\DataSiswaController', [
        'except' => ['show']
    ]);
    Route::put('/admin/verifikasiRombel/verifRombel', 'AppController\VerifikasiRombelController@verifRombel');
    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
});
=======
});
>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4

app/DataSekolah.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DataSekolah extends Model
{
    public function kota(){
        return $this->belongsTo('\App\Kota', 'id_kota');
    }
}

app/Http/Controllers/AppController/DataSekolahController.php
<?php

namespace App\Http\Controllers\AppController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Kota;
use App\DataSekolah;

class DataSekolahController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $r)
    {
        // $in = "";
        // for($i = $r->index; $i <= 10; $i++){
        //     $in .= $i;
        // }
        // $d["index"] = $in;
        $d['sekolahs'] = DataSekolah::orderBy('kode_sekolah', 'ASC')->paginate(10);
        if ($r->ajax()) {
            return view('app.dataSekolah.presult', $d);
        }
        else{
            return view('app.dataSekolah.index', $d);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $d['kotas'] = Kota::orderBy('kode', 'ASC')->get();
        return view('app.dataSekolah.add', $d);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $d = new DataSekolah;
        $d->id_kota = $request->input('id_kota');
        $d->kode_sekolah = $request->input('kode_sekolah');
        $d->npsn_sekolah = $request->input('npsn_sekolah');
        $d->nama_sekolah = $request->input('nama_sekolah');
        $d->kepala_sekolah = $request->input('kepala_sekolah');
        $d->kurikulum = $request->input('kurikulum');
        $d->alamat_sekolah = $request->input('alamat_sekolah');

        $d->save();
        
        return redirect()->route('dataSekolah.index')->with('alertCreate', $request->input('kode_sekolah'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $d['d'] = DataSekolah::find($id);
        $d['kotas'] = Kota::orderBy('kode', 'ASC')->get();
        return view('app.dataSekolah.show', $d);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $d['d'] = DataSekolah::find($id);
        $d['kotas'] = Kota::orderBy('kode', 'ASC')->get();
        return view('app.dataSekolah.edit', $d);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $d = DataSekolah::find($id);
        $d->id_kota = $request->input('id_kota');
        $d->kode_sekolah = $request->input('kode_sekolah');
        $d->npsn_sekolah = $request->input('npsn_sekolah');
        $d->nama_sekolah = $request->input('nama_sekolah');
        $d->kepala_sekolah = $request->input('kepala_sekolah');
        $d->kurikulum = $request->input('kurikulum');
        $d->alamat_sekolah = $request->input('alamat_sekolah');

        $d->save();
        
        return redirect()->route('dataSekolah.index')->with('alertCreate', $request->input('kode_sekolah'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $d = DataSekolah::find($id);
        $kode_sekolah = $d->kode_sekolah;

        $d->delete();

        return redirect()->route('dataSekolah.index')->with('alertCreate', $kode_sekolah);
    }
}

resources/views/app/dataSekolah/add.blade.php
@extends('layouts.app')

@section('contentHeader')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <!-- <h1 class="m-0 text-dark">Tambah Data Sekolah</h1> -->
            <a href="/superAdmin/dataSekolah"><h4><i class="fas fa-chevron-left"></i> Kembali</h4></a>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Sekolah</a></li>
            <li class="breadcrumb-item active">Tambah</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <!-- <a href="{{ route('dataSekolah.index') }}" class="btn btn-light text-info btn-sm">Kembali</a> -->
                        <h3 class="card-title">Tambah data Sekolah</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('dataSekolah.store') }}">
                        @csrf
                        <div class="card-body">
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Wilayah</label>
                                    <select class="form-control select2" name="id_kota" required>
                                        <option value="">&mdash;</option>
                                        @foreach($kotas as $res)
                                        <option value="{{ $res->id }}">{{ $res->nama_kota }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Kode Sekolah</label>
                                    <input type="text" class="form-control" placeholder="Kode Sekolah" name="kode_sekolah" required>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>NPSN Sekolah</label>
                                    <input type="text" class="form-control" placeholder="NPSN Sekolah" name="npsn_sekolah" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label>Kurikulum</label>
                                    <input type="text" class="form-control" placeholder="Kurikulum" name="kurikulum" required>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Nama Sekolah</label>
                                    <input type="text" class="form-control" placeholder="Nama Sekolah" name="nama_sekolah" required>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label>Kepala Sekolah</label>
                                    <input type="text" class="form-control" placeholder="Kepala Sekolah" name="kepala_sekolah" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-7">
                                <div class="form-group">
                                    <label>Alamat Sekolah</label>
                                    <textarea name="alamat_sekolah" class="form-control" required placeholder="Alamat Sekolah"></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="col-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" required>
                                <label class="form-check-label">Konfirmasi data!</label>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/app/dataSekolah/edit.blade.php
@extends('layouts.app')

@section('contentHeader')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <!-- <h1 class="m-0 text-dark">Edit Data Sekolah</h1> -->
            <a href="/superAdmin/dataSekolah"><h4><i class="fas fa-chevron-left"></i> Kembali</h4></a>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Sekolah</a></li>
            <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <!-- <a href="{{ route('dataSekolah.index') }}" class="btn btn-light text-info btn-sm">Kembali</a> -->
                        <h3 class="card-title">Edit data Sekolah</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('dataSekolah.update', $d->id) }}">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="card-body">
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Wilayah</label>
                                    <select class="form-control select2" name="id_kota" required>
                                        <option value="">&mdash;</option>
                                        @foreach($kotas as $res)
                                        @if($res->id == $d->id_kota)
                                        <option value="{{ $res->id }}" selected>{{ $res->nama_kota }}</option>
                                        @else
                                        <option value="{{ $res->id }}">{{ $res->nama_kota }}</option>
                                        @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Kode Sekolah</label>
                                    <input type="text" class="form-control" placeholder="Kode Sekolah" name="kode_sekolah" required value="{{ $d->kode_sekolah }}">
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>NPSN Sekolah</label>
                                    <input type="text" class="form-control" placeholder="NPSN Sekolah" name="npsn_sekolah" required value="{{ $d->npsn_sekolah }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label>Kurikulum</label>
                                    <input type="text" class="form-control" placeholder="Kurikulum" name="kurikulum" required value="{{ $d->kurikulum }}">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Nama Sekolah</label>
                                    <input type="text" class="form-control" placeholder="Nama Sekolah" name="nama_sekolah" required value="{{ $d->nama_sekolah }}">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label>Kepala Sekolah</label>
                                    <input type="text" class="form-control" placeholder="Kepala Sekolah" name="kepala_sekolah" required value="{{ $d->kepala_sekolah }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-7">
                                <div class="form-group">
                                    <label>Alamat Sekolah</label>
                                    <textarea name="alamat_sekolah" class="form-control" required placeholder="Alamat Sekolah">{{ $d->alamat_sekolah }}</textarea>
                                </div>
                            </div>
                        </div>

                        <div class="col-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" required>
                                <label class="form-check-label">Konfirmasi data!</label>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/app/dataSekolah/index.blade.php
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Data Sekolah</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Sekolah</a></li>
            <li class="breadcrumb-item active">Index</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <a href="{{ route('dataSekolah.create') }}" class="btn btn-primary btn-sm">Tambah Data</a>
                        </h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 200px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
            
                                <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div id="presultData">
                        @include('app.dataSekolah.presult')
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>

    @if(session('alertDestroy'))
        <script>
            $(document).Toasts('create', {
                title: 'Info',
                autohide: true,
                delay: 2000,
                class: 'bg-success',
                position: 'bottomRight',
                body: 'Berhasil Menghapus Data Sekolah <b>{{ session("alertDestroy") }}</b>'
            })
        </script>
    @elseif(session('alertCreate'))
        <script>
            $(document).Toasts('create', {
                title: 'Info',
                autohide: true,
                delay: 2000,
                class: 'bg-success',
                position: 'bottomRight',
                body: 'Berhasil Menambah Data Sekolah <b>{{ session("alertCreate") }}</b>'
            })
        </script>
    @elseif(session('alertUpdate'))
        <script>
            $(document).Toasts('create', {
                title: 'Info',
                autohide: true,
                delay: 2000,
                class: 'bg-success',
                position: 'bottomRight',
                body: 'Berhasil Memperbarui Data Sekolah <b>{{ session("alertUpdate") }}</b>'
            })
        </script>
    @endif
@endsection

resources/views/app/dataSekolah/presult.blade.php
    <div class="card-body">
        <table class="table table-bordered">
        <thead>                  
            <tr>
            <th style="width: 10px">#</th>
            <th>Wilayah</th>
            <th>Kode Sekolah</th>
            <th>Nama Sekolah</th>
            <th style="width: 150px">Aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sekolahs as $res)
            <tr>
                <td>{{ ($sekolahs->currentpage()-1) * $sekolahs->perpage() + $loop->index + 1 }}</td>
                <td>{{ $res->kota->nama_kota }}</td>
                <td>
                    <span class="badge badge-primary">{{ $res->kode_sekolah }}</span>
                </td>
                <td>
                    {{ $res->nama_sekolah }}
                </td>
                <td nowrap>
                    <a href="{{ route('dataSekolah.show', $res->id) }}" class="btn btn-success btn-sm">Detail</a>
                    <a href="{{ route('dataSekolah.edit', $res->id) }}" class="btn btn-warning btn-sm">Edit</a>
                    <a href="#" data-uri="{{ route('dataSekolah.destroy', $res->id) }}" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteCModal">Hapus</a>
                </td>
            </tr>
            @endforeach
        </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix float-right">
        {!! $sekolahs->render() !!}
    </div>

resources/views/app/dataSekolah/show.blade.php
@extends('layouts.app')

@section('contentHeader')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Detail Data Sekolah</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Sekolah</a></li>
            <li class="breadcrumb-item active">Detail</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <a href="{{ route('dataSekolah.index') }}" class="btn btn-light text-info btn-sm">Kembali</a>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label>Wilayah</label>
                                <p>{{ $d->kota->nama_kota }}</p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label>Kode Sekolah</label>
                                <p>{{ $d->kode_sekolah }}</p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label>NPSN Sekolah</label>
                                <p>{{ $d->npsn_sekolah }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label>Kurikulum</label>
                                <p>{{ $d->kurikulum }}</p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label>Nama Sekolah</label>
                                <p>{{ $d->nama_sekolah }}</p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label>Kepala Sekolah</label>
                                <p>{{ $d->kepala_sekolah }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-7">
                            <div class="form-group">
                                <label>Alamat Sekolah</label>
                                <p>{{ $d->alamat_sekolah }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection