routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Symfony\Component\Routing\Route;
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'function',  'middleware' => 'auth'], function(){
    Route::get('loggedIn', 'FunctionController@loggedIn');
});
Route::group(['prefix' => 'superAdmin',  'middleware' => 'role.superAdmin'], function(){
    Route::resource('dataSekolah', 'AppController\DataSekolahController', [
    ]);
    Route::resource('administratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataPengawas', 'AppController\DataPengawasController', [
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::post('/dataSiswa/store_excel', 'AppController\DataSiswaController@store_excel')->name('siswa_store_excel');
    Route::resource('dataSiswa', 'AppController\DataSiswaController');
    Route::resource('dataJurusan', 'AppController\DataJurusanController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");
=======

    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'guru', 'middleware' => 'role.guru'], function(){
<<<<<<< HEAD
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/dokumen', 'AppController\DataDokumenController@index')->name('dokumenGuruIndex');
    Route::post('/dokumen', 'AppController\DataDokumenController@proses_upload')->name('dokumenGuruPost');
=======


    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/upload', 'AppController\DataDokumenController@upload');
    Route::post('/upload/proses', 'AppController\DataDokumenController@proses_upload');



>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'admin', 'middleware' => 'role.admin'], function(){
<<<<<<< HEAD
    
=======


    Route::resource('dataMapel', 'AppController\DataMapelController');

    Route::resource('tahunAkademik', 'AppController\TahunAkademikController');

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
    Route::resource('AdministratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::resource('dataSiswa', 'AppController\DataSiswaController', [
        'except' => ['show']
    ]);
    Route::put('/admin/verifikasiRombel/verifRombel', 'AppController\VerifikasiRombelController@verifRombel');
    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
});
=======
});
>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4

app/DataPengawas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DataPengawas extends Model
{
    //
}

app/Http/Controllers/AppController/DataPengawasController.php
<?php

namespace App\Http\Controllers\AppController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\User;
use App\DataSekolah;

class DataPengawasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
 * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $r)
    {
        $d['dataPengawas'] = User::where('role', 'Pengawas')->paginate(10);
        $d['sekolahs'] = DataSekolah::orderBy('kode_sekolah', 'ASC')->get();
        if ($r->ajax()) {
            return view('app.dataPengawas.presult', $d);
        }
        else{
            return view('app.dataPengawas.index', $d);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $d['sekolahs'] = DataSekolah::orderBy('kode_sekolah', 'ASC')->get();
        return view('app.dataPengawas.add', $d);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $d = new User;
        $d->name = $request->input('name');
        $d->email = $request->input('email');
        $d->password = Hash::make($request->input('password'));

        $d->id_data_sekolah = implode($request->input('id_data_sekolah'), ', ');

        $d->role = "Pengawas";

        $d->save();

        return redirect()->route('dataPengawas.index')->with('alertCreate', $request->input('kode_sekolah'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $d['d'] = User::find($id);
        $d['sekolahs'] = DataSekolah::orderBy('kode_sekolah', 'ASC')->get();
        return view('app.dataPengawas.show', $d);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $d['d'] = User::find($id);
        $d['sekolahs'] = DataSekolah::orderBy('kode_sekolah', 'ASC')->get();
        return view('app.dataPengawas.edit', $d);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $d = User::find($id);
        $d->name = $request->input('name');
        $d->email = $request->input('email');

        if(!empty($request->input('password'))){
            $d->password = Hash::make($request->input('password'));
        }

        $d->id_data_sekolah = implode($request->input('id_data_sekolah'), ', ');

        $d->role = "Pengawas";

        $d->save();

        return redirect()->route('dataPengawas.index')->with('alertCreate', $request->input('kode_sekolah'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $d = User::find($id);
        $email = $d->email;

        $d->delete();

        return redirect()->route('dataPengawas.index')->with('alertCreate', $email);
    }
}

resources/views/app/dataPengawas/add.blade.php
@extends('layouts.app')

@section('contentHeader')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Tambah Data Pengawas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Pengawas</a></li>
            <li class="breadcrumb-item active">Tambah</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <a href="{{ route('dataPengawas.index') }}" class="btn btn-light text-info btn-sm">Kembali</a>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('dataPengawas.store') }}">
                        @csrf
                        <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Mengawas Sekolah</label>
                                    <select class="select2" name="id_data_sekolah[]" multiple="multiple" data-placeholder="Mengawas Sekolah" style="width: 100%;">
                                        <option value="">&mdash;</option>
                                        @foreach($sekolahs as $res)
                                        <option value="{{ $res->id }}">{{ $res->nama_sekolah }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Nama Pengawas</label>
                                    <input type="text" class="form-control" placeholder="Nama Pengawas" name="name" required>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="text" class="form-control" placeholder="Email" name="email" required>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="text" class="form-control" placeholder="Password" name="password" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" required>
                                <label class="form-check-label">Konfirmasi data!</label>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/app/dataPengawas/edit.blade.php
@extends('layouts.app')

@section('contentHeader')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Edit Data Pengawas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Pengawas</a></li>
            <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <a href="{{ route('dataPengawas.index') }}" class="btn btn-light text-info btn-sm">Kembali</a>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('dataPengawas.update', $d->id) }}">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Mengawas Sekolah</label>
                                    <select class="select2" name="id_data_sekolah[]" multiple="multiple" data-placeholder="Mengawas Sekolah" style="width: 100%;">
                                        <option value="">&mdash;</option>
                                        @php
                                            $de = explode(', ', $d->id_data_sekolah);
                                        @endphp
                                            @foreach($sekolahs as $res)

                                            @if(in_array($res->id,$de))
                                                <option value="{{ $res->id }}" selected>{{ $res->nama_sekolah }}</option>
                                            @else
                                                <option value="{{ $res->id }}">{{ $res->nama_sekolah }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Nama Pengawas</label>
                                    <input type="text" class="form-control" placeholder="Nama Pengawas" name="name" required value="{{ $d->name }}">
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="text" class="form-control" placeholder="Email" name="email" required value="{{ $d->email }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                <button id="btnChangePw" class="btn btn-warning btn-sm">Ganti Password</button>
                                <button id="btnClosePw" class="btn btn-danger btn-sm">Batal</button>
                                <div id="pwWrapper" class="form-group">
                                    <label>Password</label>
                                    <input id="passwordInput" type="text" class="form-control" placeholder="Password" name="password">
                                </div>
                            </div>    
                        </div>
                        <br>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" required>
                            <label class="form-check-label">Konfirmasi data!</label>
                        </div>
                        <br>
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>
    <script>
        $('#btnClosePw').hide()
        $('#pwWrapper').hide()
        $('#btnChangePw').click(function(e){
            e.preventDefault()
            $('#pwWrapper').show("slow")
            $(this).hide()
            $('#btnClosePw').show()
        })
        $('#btnClosePw').click(function(e){
            e.preventDefault()
            $('#pwWrapper').slideUp("slow")
            $(this).hide()
            $('#btnChangePw').show()
            $('#passwordInput').val('')
        })

    </script>
@endsection

resources/views/app/dataPengawas/index.blade.php
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Data Pengawas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Pengawas</a></li>
            <li class="breadcrumb-item active">Index</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <a href="{{ route('dataPengawas.create') }}" class="btn btn-primary btn-sm">Tambah Data</a>
                        </h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 200px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
            
                                <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div id="presultData">
                        @include('app.dataPengawas.presult')
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>

    @if(session('alertDestroy'))
        <script>
            $(document).Toasts('create', {
                title: 'Info',
                autohide: true,
                delay: 2000,
                class: 'bg-success',
                position: 'bottomRight',
                body: 'Berhasil Menghapus Data Pengawas <b>{{ session("alertDestroy") }}</b>'
            })
        </script>
    @elseif(session('alertCreate'))
        <script>
            $(document).Toasts('create', {
                title: 'Info',
                autohide: true,
                delay: 2000,
                class: 'bg-success',
                position: 'bottomRight',
                body: 'Berhasil Menambah Data Pengawas <b>{{ session("alertCreate") }}</b>'
            })
        </script>
    @elseif(session('alertUpdate'))
        <script>
            $(document).Toasts('create', {
                title: 'Info',
                autohide: true,
                delay: 2000,
                class: 'bg-success',
                position: 'bottomRight',
                body: 'Berhasil Memperbarui Data Pengawas <b>{{ session("alertUpdate") }}</b>'
            })
        </script>
    @endif
@endsection

resources/views/app/dataPengawas/presult.blade.php
    <div class="card-body">
        <table class="table table-bordered">
        <thead>                  
            <tr>
            <th style="width: 10px">#</th>
            <th>Nama Pengawas</th>
            <th>Email</th>
            <th>Daftar Sekolah Binaan</th>
            <th style="width: 150px">Aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach($dataPengawas as $res)
            <tr>
                <td>{{ ($dataPengawas->currentpage()-1) * $dataPengawas->perpage() + $loop->index + 1 }}</td>
                <td>{{ $res->name }}</td>
                <td>{{ $res->email }}</td>
                <td>
                    @php
                    $d = explode(', ', $res->id_data_sekolah);
                    $e = "";
                    @endphp

                    @foreach($sekolahs as $rs)
                        @if(in_array($rs->id,$d))
                            @php
                            $e .= "<span class='badge badge-primary'>".$rs->nama_sekolah."</span> ";
                            @endphp
                        @endif
                    @endforeach
                    
                    @if(strlen($e) > 200)
                        {!! substr($e,0,200) !!}
                        ....
                        </span>
                    @else
                        {!! $e !!}
                    @endif
                </td>
                <td nowrap>
                    <a href="{{ route('dataPengawas.show', $res->id) }}" class="btn btn-success btn-sm">Detail</a>

                    <a href="{{ route('dataPengawas.edit', $res->id) }}" class="btn btn-warning btn-sm">Edit</a>
                    <a href="#" data-uri="{{ route('dataPengawas.destroy', $res->id) }}" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteCModal">Hapus</a>

                </td>
            </tr>
            @endforeach
        </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix float-right">
        {!! $dataPengawas->render() !!}
    </div>

resources/views/app/dataPengawas/show.blade.php
@extends('layouts.app')

@section('contentHeader')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Detail Data Pengawas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Pengawas</a></li>
            <li class="breadcrumb-item active">Detail</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <a href="{{ route('dataPengawas.index') }}" class="btn btn-light text-info btn-sm">Kembali</a>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <label>Nama Pengawas</label>
                                <p>{{ $d->name }}</p>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label>Email</label>
                                <p>{{ $d->email }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label>Daftar Sekolah Binaan</label>
                                <ul>
                                    @php
                                        $de = explode(', ', $d->id_data_sekolah);
                                    @endphp
                                    @foreach($sekolahs as $res)

                                        @if(in_array($res->id,$de))
                                            <li>
                                                <div>{{ $res->nama_sekolah }}</div>
                                            </li>
                                        @endif
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        @php
                            $df = $d->created_at;
                            $t = $df->format('Y-m-d');
                        @endphp
                        @include('_____FUNCTION.tanggal-indo')
                        <div class="col-12">
                           <i>Bergabung pada tanggal
                            <span class="color-danger">{{ tgl_indo($t) }}</span>
                           </i>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            </div>
    </div><!-- /.container-fluid -->
    </section>
    <script>
        $('#btnClosePw').hide()
        $('#pwWrapper').hide()
        $('#btnChangePw').click(function(e){
            e.preventDefault()
            $('#pwWrapper').show("slow")
            $(this).hide()
            $('#btnClosePw').show()
        })
        $('#btnClosePw').click(function(e){
            e.preventDefault()
            $('#pwWrapper').slideUp("slow")
            $(this).hide()
            $('#btnChangePw').show()
            $('#passwordInput').val('')
        })

    </script>
@endsection