routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Symfony\Component\Routing\Route;
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'function',  'middleware' => 'auth'], function(){
    Route::get('loggedIn', 'FunctionController@loggedIn');
});
Route::group(['prefix' => 'superAdmin',  'middleware' => 'role.superAdmin'], function(){
    Route::resource('dataSekolah', 'AppController\DataSekolahController', [
    ]);
    Route::resource('administratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataPengawas', 'AppController\DataPengawasController', [
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::post('/dataSiswa/store_excel', 'AppController\DataSiswaController@store_excel')->name('siswa_store_excel');
    Route::resource('dataSiswa', 'AppController\DataSiswaController');
    Route::resource('dataJurusan', 'AppController\DataJurusanController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");
=======

    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'guru', 'middleware' => 'role.guru'], function(){
<<<<<<< HEAD
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/dokumen', 'AppController\DataDokumenController@index')->name('dokumenGuruIndex');
    Route::post('/dokumen', 'AppController\DataDokumenController@proses_upload')->name('dokumenGuruPost');
=======


    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/upload', 'AppController\DataDokumenController@upload');
    Route::post('/upload/proses', 'AppController\DataDokumenController@proses_upload');



>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'admin', 'middleware' => 'role.admin'], function(){
<<<<<<< HEAD
    
=======


    Route::resource('dataMapel', 'AppController\DataMapelController');

    Route::resource('tahunAkademik', 'AppController\TahunAkademikController');

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
    Route::resource('AdministratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::resource('dataSiswa', 'AppController\DataSiswaController', [
        'except' => ['show']
    ]);
    Route::put('/admin/verifikasiRombel/verifRombel', 'AppController\VerifikasiRombelController@verifRombel');
    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
});
=======
});
>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4

app/DataGuru.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DataGuru extends Model
{
    protected $table = 'guru';
}

app/Http/Controllers/AppController/DataGuruController.php
<?php

namespace App\Http\Controllers\AppController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\DataGuru;


class DataGuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $r)
    {
        $guru = DataGuru::orderBy('nip','DESC')->paginate(10);

        if ($r->ajax()) {
            return view('app.dataGuru.presult', compact('guru'));
        }
        else{
            return view('app.dataGuru.index', compact('guru'));
        }

        // $guru1 = DataGuru::orderBy('nama')->where('nip','<>', '')->get();
        // $guru2 = DataGuru::orderBy('nama')->where('nip', '')->get();

        // $data['guru'] = '';
        // $data['guru'] .= $guru1;
        // $data['guru'] .= $guru2;

        // return view('app.dataGuru.index', ['guru'=>$guru1]);
        // dd($data);
        
       
        return view('app.dataGuru.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('app.dataGuru.create');   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $d = new DataGuru;
        // $d->id = $request->input('id');
        $d->nama = $request->input('nama');
        $d->nip = $request->input('nip');
        $d->nuptk = $request->input('NULL');
        $d->status_kepegawaian = $request->input('status_kepegawaian');

        $d->save();
        
        
        return redirect()->route('dataGuru.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $guru = DataGuru::findOrFail($id);
        // return view('app.dataGuru.edit', ['guru' => $guru]);
        return view('app.dataGuru.edit', compact('guru'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $d = DataGuru::find($id);
        // $d->id = $request->input('id');
        // $d->nama = $request->input('nama');
        // $d->nip = $request->input('nip');
        // $d->status_kepegawaian = $request->input('status_kepegawaian');

        // $d->save();
        
        // return redirect()->route('dataGuru.index');

        $validatedData = $request->validate([
            'nama' => 'required|max:255',
            'nip' => 'required|max:255',
            'status_kepegawaian' => 'required|max:255',
        ]);
        DataGuru::whereId($id)->update($validatedData);

        return redirect()->route('dataGuru.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $guru = DataGuru::find($id);
        $guru->delete();

        return redirect()->route('dataGuru.index');
    }
}

resources/views/app/dataGuru/create.blade.php
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <!-- <h1 class="m-0 text-dark"><a href="/superAdmin/dataGuru/"><i class="fas fa-chevron-left"></i></a> Tambah Data Guru</h1> -->
            <a href="/superAdmin/dataGuru"><h4><i class="fas fa-chevron-left"></i> Kembali</h4></a>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Guru</a></li>
            <li class="breadcrumb-item active">Create</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
    <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Tambah data Guru</h3>
                        <div class="card-tools">
                            <button class="btn btn-tool" type="button" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                    <form role="form" method="POST" action="{{ route('dataGuru.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                        <label for="">Nama</label>
                                        <input type="text" class="form-control" placeholder="nama" name="nama">
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="">NIP</label>
                                            <input type="text" class="form-control" placeholder="nip" name="nip">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="">Status Kepegawaian</label>
                                            <input type="text" class="form-control" placeholder="Status Kepegawaian" name="status_kepegawaian">
                                        </div>
                                    </div>
                            </div>
                            <div class="form-group right">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/app/dataGuru/edit.blade.php
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <!-- <h1 class="m-0 text-dark"><a href="/superAdmin/dataGuru/"><i class="fas fa-chevron-left"></i></a> Tambah Data Guru</h1> -->
            <a href="/superAdmin/dataGuru"><h4><i class="fas fa-chevron-left"></i> Kembali</h4></a>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Guru</a></li>
            <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
    <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit data Guru</h3>
                        <div class="card-tools">
                            <button class="btn btn-tool" type="button" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                    <form method="post" action="{{ route('dataGuru.update', $guru->id) }}">
                        @csrf
                            @method('PATCH')
                        <div class="row">
                                <div class="col-md-6">
                                    <label for="">Nama</label>
                                    <input type="text" class="form-control" placeholder="nama" name="nama" value="{{$guru->nama}}">
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="">NIP</label>
                                        <input type="text" class="form-control" placeholder="nip" name="nip" value="{{$guru->nip}}">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="">Status Kepegawaian</label>
                                        <input type="text" class="form-control" placeholder="Status Kepegawaian" name="status_kepegawaian" value="{{$guru->status_kepegawaian}}">
                                    </div>
                                </div>
                                <!-- <div class="col-md-3 hidden">
                                    <label for="">Id</label>
                                    <input type="text" name="" id="" class="form-control">
                                </div> -->
                                <!-- <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="">Nama</label>
                                        <input type="text" class="form-control" placeholder="Nama" value="{{ $guru->nama }}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="">NIP</label>
                                        <input type="text" class="form-control" placeholder="NIP">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="">Jenis PTK</label>
                                        <input type="text" class="form-control" placeholder="Jenis PTK">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="">Status</label>
                                        <input type="text" class="form-control" placeholder="Status">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="">Agama</label>
                                        <select name="" id="" placeholder="Agama" class="form-control">
                                            <option value="Islam">Islam</option>
                                            <option value="Protestan">Protestan</option>
                                            <option value="Katholik">Katholik</option>
                                            <option value="Hindu">Hindu</option>
                                            <option value="Buddha">Buddha</option>
                                            <option value="Konghucu">Konghucu</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="">Tempat Lahir</label>
                                        <input type="text" class="form-control" placeholder="Tempat Lahir">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="">Tanggal Lahir</label>
                                        <input type="date" class="form-control" placeholder="Tanggal Lahir">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="">Alamat</label>
                                        <textarea name="" id="" cols="30" rows="5" class="form-control" placeholder="Alamat"></textarea>
                                    </div>
                                </div> -->
                            </div>
                            <div class="form-group right">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/app/dataGuru/index.blade.php
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Data Guru</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Data Guru</a></li>
            <li class="breadcrumb-item active">Index</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
    <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <a href="{{ url('superAdmin/dataGuru/create') }}" class="btn btn-primary btn-sm">Tambah Data</a>
                            <a href="{{ url('') }}" class="btn btn-success btn-sm">Tambah data dengan Excel</a>
                            <a href="{{ url('') }}" class="btn btn-warning btn-sm">Upload File</a>
                        </h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 200px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
            
                                <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="presultData">
                        @include('app.dataGuru.presult')
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/app/dataGuru/presult.blade.php
<!-- /.card-header -->
<div class="card-body">
                        <table class="table table-bordered">
                        <thead>                  
                            <tr>
                            <th style="width: 10px">#</th>
                            <th>Nama</th>
                            <th>NIP</th>
                            <th>Status Kepegawaian</th>
                            <th style="width: 150px">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- <tr>
                                <td>1</td>
                                <td>Lucky Adhitya</td>
                                <td>1092</td>
                                <td>Aktif</td>
                                <td>Islam</td>
                                <td>
                                    <a href="" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="" class="btn btn-danger btn-sm">Hapus</a>
                                </td>
                            </tr> -->
                            @foreach($guru as $d)
                            <tr>
                                <td>{{ ($guru->currentpage()-1) * $guru->perpage() + $loop->index + 1 }}</td>
                                <td>{{ $d->nama }}</td>
                                <td>{{ $d->nip }}</td>
                                <td>{{ $d->status_kepegawaian }}</td>
                                <td>
                                    <a href="{{ route('dataGuru.edit', $d->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="#" data-uri="{{ route('dataGuru.destroy', $d->id) }}" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteCModal">Hapus</a>
                                </td>
                            </tr>
                            @endforeach
                            <!-- <tr>
                                <td>1</td>
                                <td>Jakarta Utara 1</td>
                                <td>
                                    <span class="badge badge-primary">032222</span>
                                </td>
                                <td>
                                    SMK Negeri 10 Jakarta
                                </td>
                                <td>
                                    <a href="" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="" class="btn btn-danger btn-sm">Hapus</a>
                                </td>
                            </tr> -->
                        </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        {!! $guru->render() !!}
                    </div>