routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Symfony\Component\Routing\Route;
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'function',  'middleware' => 'auth'], function(){
    Route::get('loggedIn', 'FunctionController@loggedIn');
});
Route::group(['prefix' => 'superAdmin',  'middleware' => 'role.superAdmin'], function(){
    Route::resource('dataSekolah', 'AppController\DataSekolahController', [
    ]);
    Route::resource('administratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataPengawas', 'AppController\DataPengawasController', [
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::post('/dataSiswa/store_excel', 'AppController\DataSiswaController@store_excel')->name('siswa_store_excel');
    Route::resource('dataSiswa', 'AppController\DataSiswaController');
    Route::resource('dataJurusan', 'AppController\DataJurusanController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");
=======

    // Route::post("/verifikasiRombel/verif_rombel", "AppController\VerifikasiRombelController@verif_rombel");

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'guru', 'middleware' => 'role.guru'], function(){
<<<<<<< HEAD
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/dokumen', 'AppController\DataDokumenController@index')->name('dokumenGuruIndex');
    Route::post('/dokumen', 'AppController\DataDokumenController@proses_upload')->name('dokumenGuruPost');
=======


    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
    Route::resource('dataDokumen', 'AppController\DataDokumenController', [
        'except' => ['show']
    ]);
    Route::get('/upload', 'AppController\DataDokumenController@upload');
    Route::post('/upload/proses', 'AppController\DataDokumenController@proses_upload');



>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
});
Route::group(['prefix' => 'admin', 'middleware' => 'role.admin'], function(){
<<<<<<< HEAD
    
=======


    Route::resource('dataMapel', 'AppController\DataMapelController');

    Route::resource('tahunAkademik', 'AppController\TahunAkademikController');

>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4
    Route::resource('AdministratorSekolah', 'AppController\AdministratorSekolahController', [
        'except' => ['show']
    ]);
    Route::resource('dataGuru', 'AppController\DataGuruController', [
        'except' => ['show']
    ]);
    Route::resource('dataSiswa', 'AppController\DataSiswaController', [
        'except' => ['show']
    ]);
    Route::put('/admin/verifikasiRombel/verifRombel', 'AppController\VerifikasiRombelController@verifRombel');
    Route::resource('verifikasiRombel', 'AppController\VerifikasiRombelController', [
        'except' => ['show']
    ]);
<<<<<<< HEAD
});
=======
});
>>>>>>> 8080ce61beff0433a592ccef5ce1d10d61e878f4

app/Http/Controllers/AppController/VerifikasiRombelController.php
<?php

namespace App\Http\Controllers\AppController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Jurusan;
use App\Siswa;

class VerifikasiRombelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $d['rombels'] = Siswa::select('rombel_saat_ini')->groupBy('rombel_saat_ini')->where('jurusan', '')->get();
        $d['jurusans'] = Jurusan::orderBy('kode_jurusan', 'ASC')->get();
        return view('app.verifikasiRombel.index', $d);
    }

    public function import(){
        
    }

    public function process_import(){

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rombel = $request->input('rombel');
        $tingkatan = $request->input('tingkatan');
        $jurusan = $request->input('jurusan');

        Siswa::where('rombel_saat_ini', $rombel)->update(['tingkatan' => $tingkatan, 'jurusan'=>$jurusan]);

        return redirect()->route('verifikasiRombel.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    public function verifRombel(Request $request){
        $rombel = $request->input('rombel');
        $tingkatan = $request->input('tingkatan');
        $jurusan = $request->input('jurusan');

        Siswa::where('rombel_saat_ini', $rombel)->update(['tingkatan' => $tingkatan, 'jurusan'=>$jurusan]);

        return redirect()->url('verifikasiRombel.index');
    }

    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app/verifikasiRombel/import.blade.php
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <a href="{{ url('/superAdmin/verifikasiRombel') }}">
                    <h3><i class="fas fa-chevron-left"></i> Kembali</h3>
                </a>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Verifikasi Rombel</a></li>
                    <li class="breadcrumb-item active">Import</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Import Rombel
                            <a href="#!" class="mx-3 btn btn-success btn-sm">Impor Rombel </a>
                        </h3>
                        <div class="card-tools">
                            <button class="btn btn-tool" type="button" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ url('superAdmin/verifikasiRombel/process_import') }}" method="post">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                                </div>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                                    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
</section>
@endsection

resources/views/app/verifikasiRombel/index.blade.php
<!--  -->
<!-- Modal -->
<div class="modal fade" id="modalImport" tabindex="-1" role="dialog" aria-labelledby="modalImportLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Impor data Rombel</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ url('/superAdmin/verifikasiRombel/store_excel') }}" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="">File Excel</label>
                        <input type="file" name="file" id="" class="">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--  -->
@extends('layouts.app')

@section('contentHeader')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Verifikasi Rombel</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Verifikasi Rombel</a></li>
                    <li class="breadcrumb-item active">Index</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection
@section('mainContent')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Verifikasi data Rombel
                        </h3>
                        <div class="card-tools">
                            <button class="btn btn-tool" type="button" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('verifikasiRombel.store') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-md-2 col-sm-12">
                                    <div class="form-group">
                                        <label for="">Rombel</label>
                                        <select name="rombel" id="" class="form-control select2">
                                            <option value="">&mdash;</option>
                                            @foreach($rombels as $res)
                                            <option value="{{ $res->rombel_saat_ini }}">{{ $res->rombel_saat_ini }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2 col-sm-12">
                                    <div class="form-group">
                                        <label for="">Tingkatan</label>
                                        <select name="tingkatan" id="" class="form-control select2">
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                            <option value="13">13</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-12">
                                    <div class="form-group">
                                        <label for="">Jurusan</label>
                                        <select class="form-control select2" name="jurusan" required>
                                            <option value="">&mdash;</option>
                                            @foreach($jurusans as $res)
                                            <option value="{{ $res->nama_jurusan }}">{{ $res->kode_jurusan }} - {{ $res->nama_jurusan }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group right">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
</section>
@endsection